name: Build Project Files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout into temporary folder
      uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: Build and commit static files
      run: |
        npm install
        npm run build
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git rm -r --cached .
        mv README_build.md README.md
        git add --force dist/
        git add --force README.md
        git diff-index --quiet HEAD || git commit -m "*compile dist/"
        git push --force origin HEAD:build