name: Build Project Files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and commit static files
      run: |
        npm install
        npm run build
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -f dist/
        git diff-index --quiet HEAD || git commit -m "*compile dist/"
        git push origin HEAD:build

    
