name: Build Project Files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout into temporary folder
      uses: actions/checkout@v3
      with:
        ref: 'master'
        path: 'temp'
    - name: Build and commit static files
      run: |
        cd temp
        npm install
        npm run build
        cd ../
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        cp -r temp/dist ./dist
        git add -A --force dist/
        git diff-index --quiet HEAD || git commit -m "*compile dist/"
        git push origin HEAD:build

    
