name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simulationsprojekt:$(date +%d-%m-%y)
      
    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}" docker.io

    - name: Tag the Docker image
      run: docker tag simulationsprojekt:$(date +%d-%m-%y) jannickbath/simulationsprojekt:$(date +%d-%m-%y)

    - name: Push to Docker Hub
      run: docker push jannickbath/simulationsprojekt:$(date +%d-%m-%y)

    - name: Compile and Commit static files
      run: |
        npm install
        npm run build
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "*compile dist/"
        git push
